parameters:
#    pit_wall_pagina_principal.example.class: PitWall\PaginaPrincipalBundle\Example

services:
#    pit_wall_pagina_principal.example:
#        class: %pit_wall_pagina_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
