pagina_estatica:
    resource: "@PitWallPaginasEstaticasBundle/Resources/config/routing.yml"
    prefix:   /

portada:
    resource: "@PitWallPaginaPrincipalBundle/Resources/config/routing.yml"
    prefix:   /

